


#ifndef REX_ATOMIC_INTERNAL_COMPILER_SIGNAL_FENCE_H
#define REX_ATOMIC_INTERNAL_COMPILER_SIGNAL_FENCE_H

#pragma once


/////////////////////////////////////////////////////////////////////////////////
//
// void REX_COMPILER_ATOMIC_SIGNAL_FENCE_*()
//
#if defined(REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELAXED)
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELAXED_AVAILABLE 1
#else
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELAXED_AVAILABLE 0
#endif

#if defined(REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQUIRE)
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQUIRE_AVAILABLE 1
#else
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQUIRE_AVAILABLE 0
#endif

#if defined(REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELEASE)
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELEASE_AVAILABLE 1
#else
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_RELEASE_AVAILABLE 0
#endif

#if defined(REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQ_REL)
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQ_REL_AVAILABLE 1
#else
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_ACQ_REL_AVAILABLE 0
#endif

#if defined(REX_COMPILER_ATOMIC_SIGNAL_FENCE_SEQ_CST)
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_SEQ_CST_AVAILABLE 1
#else
	#define REX_COMPILER_ATOMIC_SIGNAL_FENCE_SEQ_CST_AVAILABLE 0
#endif


#endif /* REX_ATOMIC_INTERNAL_COMPILER_SIGNAL_FENCE_H */
