


#ifndef REX_ATOMIC_INTERNAL_ARCH_COMPILER_BARRIER_H
#define REX_ATOMIC_INTERNAL_ARCH_COMPILER_BARRIER_H

#pragma once


#define REX_ARCH_ATOMIC_COMPILER_BARRIER_AVAILABLE 0

#define REX_ARCH_ATOMIC_COMPILER_BARRIER_DATA_DEPENDENCY_AVAILABLE 0


#endif /* REX_ATOMIC_INTERNAL_ARCH_COMPILER_BARRIER_H */
