

# This file was automatically generated by "create_project.py"
# Command: generate_project(type project_name solution_folder project_folder pch_header_name = project_folder pch_src_name = project_folder)
# Example: generate_project(static CoreLibs 1_common core_libs)


# include path: ${REX_STL_DIR}/include/0_extern/rex_std
# src path: ${REX_STL_DIR}/src/0_extern/rex_std


# Project Name Project
# -------------------------
file(GLOB_RECURSE RexStd_LIBS_INC    ${REX_STL_DIR}/include/0_extern/rex_std/*.h)
file(GLOB_RECURSE RexStd_LIBS_SRC    ${REX_STL_DIR}/src/0_extern/rex_std/*.cpp)


# Create the project filters
GROUPSOURCES(${REX_STL_DIR}/include/0_extern/rex_std include)
GROUPSOURCES(${REX_STL_DIR}/src/0_extern/rex_std src)


# Create the project
add_library(RexStd STATIC ${RexStd_LIBS_INC} ${RexStd_LIBS_SRC})

# Compiler definitions
# add_compile_definitions("REX_ENABLE_LOGGING")
# add_compile_definitions("REX_ENABLE_ASSERTS")

# Set the include directories
target_include_directories(RexStd PUBLIC ${REX_STL_DIR}/include/0_extern)

# Set the static libraries you need to link to 
IF(MSVC)
	target_link_libraries(RexStd "Dbghelp.lib")
ENDIF()

# Set project properties
set_target_properties(RexStd PROPERTIES FOLDER                                         0_extern/rex_std)   						# solution folder
set_target_properties(RexStd PROPERTIES DEFINE_SYMBOL                                  "" )                     		# defines
IF(MSVC)
	set_target_properties(RexStd PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY                ${OUTPUT_BINDIR})        		# working directory


	set_target_properties(RexStd PROPERTIES VS_GLOBAL_EnableUnitySupport                 True)                    		# unit builds on visual studio
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_IncludeInUnityFile                 True)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_OrderInUnityFile                   100)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_CombineFilesOnlyFromTheSameFolder  false)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_MinFilesInUnityFile                2)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_MaxFilesInUnityFile                0)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_MinUnityFiles                      1)
	set_target_properties(RexStd PROPERTIES VS_GLOBAL_UnityFilesDirectory                .)
ENDIF()


# Compiler options
if (MSVC)
target_compile_options(RexStd PRIVATE /W4 /WX /MP)
endif()

# add the clang tools post build check
add_custom_command(TARGET RexStd POST_BUILD COMMAND "${CMAKE_SOURCE_DIR}/scripts/run_clang_tools.py")
