

# This file was automatically generated by "create_project.py"
# Command: generate_project(type project_name solution_folder project_folder pch_header_name = project_folder pch_src_name = project_folder)
# Example: generate_project(static CoreLibs 1_common core_libs)


# include path: ${CMAKE_SOURCE_DIR}/source/include/0_extern/rex_stl/rex_std_exe
# src path: ${CMAKE_SOURCE_DIR}/source/src/0_extern/rex_stl/rex_std_exe


# Project Name Project
# -------------------------
file(GLOB_RECURSE RexStdExe_LIBS_INC    ${CMAKE_SOURCE_DIR}/source/include/0_extern/rex_std_exe/*.h)
file(GLOB_RECURSE RexStdExe_LIBS_SRC    ${CMAKE_SOURCE_DIR}/source/src/0_extern/rex_std_exe/*.cpp)


# Create the project filters
GROUPSOURCES(${CMAKE_SOURCE_DIR}/source/include/0_extern/rex_std_exe include)
GROUPSOURCES(${CMAKE_SOURCE_DIR}/source/src/0_extern/rex_std_exe src)


# Create the project
add_executable(RexStdExe  ${RexStdExe_LIBS_INC} ${RexStdExe_LIBS_SRC})


# Set the include directories
target_include_directories(RexStdExe PUBLIC ${CMAKE_SOURCE_DIR}/source/include/0_extern/rex_std_exe)

# Set the link libraries
target_link_libraries(RexStdExe PUBLIC RexStd)
# target_link_libraries(RexStdExe PUBLIC RexStdExtra)

# Set project properties
set_target_properties(RexStdExe PROPERTIES FOLDER                                         0_extern/rex_std)   		# solution folder
set_target_properties(RexStdExe PROPERTIES DEFINE_SYMBOL                                  "" )                     		# defines
IF(MSVC)
	set_target_properties(RexStdExe PROPERTIES VS_DEBUGGER_WORKING_DIRECTORY                ${OUTPUT_BINDIR})        		# working directory
	set_target_properties(RexStdExe PROPERTIES ARCHIVE_OUTPUT_DIRECTORY                     ${OUTPUT_BINDIR})        		# output directory
	set_target_properties(RexStdExe PROPERTIES LIBRARY_OUTPUT_DIRECTORY                     ${OUTPUT_BINDIR})        		# output directory
	set_target_properties(RexStdExe PROPERTIES RUNTIME_OUTPUT_DIRECTORY                     ${OUTPUT_BINDIR})        		# output directory


	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_EnableUnitySupport                 True)                    		# unit builds on visual studio
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_IncludeInUnityFile                 True)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_OrderInUnityFile                   100)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_CombineFilesOnlyFromTheSameFolder  false)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_MinFilesInUnityFile                2)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_MaxFilesInUnityFile                0)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_MinUnityFiles                      1)
	set_target_properties(RexStdExe PROPERTIES VS_GLOBAL_UnityFilesDirectory                .)
ENDIF()


# Compiler options
IF(MSVC)
	target_compile_options(RexStdExe PRIVATE /W4 /WX /MP)


ENDIF()
