#!/usr/bin/env python                                                                    
import os
import regis.util
import regis.diagnostics

def main():
  regis.diagnostics.log_info(f"running post-merge hook")

  root = regis.util.find_root()
  if os.system(f"py {os.path.join(root, '_rex.py')} setup") == 0:
    os.system(f"py {os.path.join(root, '_rex.py')} generate")
  else:
    regis.diagnostics.log_err("setup failed.")

if __name__ == "__main__":
  main()