#!/usr/bin/env python                                                                    

import os
import subprocess
import regis.run_clang_tools
import regis.util
import regis.git
import regis.test
import regis.diagnostics
import regis.rex_json

def main():
  regis.diagnostics.log_info(f"running pre-commit hook")

  files = regis.git.get_staged_files()

  regis.git.cache_commit_changes(regis.git.get_local_branchname(), files)
  exit(0)

if __name__ == "__main__":
  main()