#!/usr/bin/env python                                                                    

import sys
import regis.util
from git import Repo

def __fail_commit():
	exit(1)

def __pass_commit():
	exit(0)

def __get_commit_msg():
	git_commit_message_file = sys.argv[1]

	f = open(git_commit_message_file)
	return f.read()

def __change_commit_msg(msg):
	git_commit_message_file = sys.argv[1]
	f = open(git_commit_message_file, "w")
	f.truncate()
	f.write(msg)
	f.close()

def main():
	commit_msg = __get_commit_msg()
	repo = Repo(regis.util.find_root())

	new_msg = f"[{repo.active_branch}] {commit_msg}"
	__change_commit_msg(new_msg)

	__pass_commit()

if __name__ == "__main__":
	main()